version: "3.8"
services:
  mysql_server:
    image: mysql:8.0-bullseye
    hostname: mysql_server
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - "3306:3306"
    volumes:
      - D:/.mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    depends_on:
      - mysql_server
    restart: always
    ports:
      - "8080:80"